# frozen_string_literal: true

source 'https://rubygems.org'

gem 'base64', '~> 0.2.0'
gem 'bigdecimal', '~> 3.1'
gem 'dotenv', '~> 3.1'
gem 'forme', '~> 2.6'
gem 'logger', '~> 1.6'
gem 'passenger', '~> 6.0'
gem 'pry', '~> 0.15.0'
gem 'rack-timeout', '~> 0.7.0'
gem 'rackup', '~> 2.2'
gem 'reline', '~> 0.5.12'
gem 'roda', '~> 3.86'
gem 'roda-i18n'
gem 'rubocop', '~> 1.69'
gem 'rubyzip', '~> 2.3'
gem 'sass-embedded', '~> 1.81'
gem 'tilt', '~> 2.4'
