# frozen_string_literal: true

source 'https://rubygems.org'

gem 'base64', '~> 0.3.0'
gem 'bigdecimal', '~> 3.2'
gem 'dotenv', '~> 3.1'
gem 'forme', '~> 2.6'
gem 'logger', '~> 1.7'
gem 'ostruct', '~> 0.6.3'
gem 'passenger', '~> 6.0'
gem 'pry', '~> 0.15.2'
gem 'rack-timeout', '~> 0.7.0'
gem 'rackup', '~> 2.2'
gem 'reline', '~> 0.6.2'
gem 'roda', '~> 3.95'
gem 'roda-i18n'
gem 'rubocop', '~> 1.79'
gem 'rubyzip', '~> 2.4'
gem 'sass-embedded', '~> 1.90'
gem 'tilt', '~> 2.6'
